function dataf = EEGhighpass(data, lowF)
%BANDPASS Returns a discrete-time filter object.


% M-File generated by MATLAB(R) 7.9 and the Signal Processing Toolbox 6.12.
%
% Generated on: 18-Oct-2009 19:22:31
%

% Butterworth Bandpass filter designed using FDESIGN.BANDPASS.

% All frequency values are in Hz.
N    = 6;     % Order
F3dB = 1;     %
Fs   = 1389;  % Sampling Frequency

h = fdesign.highpass('n,f3db', N, F3dB, Fs);

Hd = design(h, 'butter');

% Get the transfer function values.
[b_60hz, a_60hz] = tf(Hd);

dataf = zeros(size(data));

for i = 1:size(data,1)
    dataf(i,:) = filtfilt(b_60hz,a_60hz,data(i,:));
end



% [EOF]
