function Hd = EEGhighpass2
%EEGHIGHPASS2 Returns a discrete-time filter object.

%
% M-File generated by MATLAB(R) 7.9 and the Signal Processing Toolbox 6.12.
%
% Generated on: 06-Mar-2010 21:55:14
%

N    = 6;     % Order
F3dB = 1;     %
Fs   = 1388;  % Sampling Frequency

h = fdesign.highpass('n,f3db', N, F3dB, Fs);

Hd = design(h, 'butter');



% [EOF]
