function jointnames = whichJointNames(Markerset_name)
%  WHICHJOINTNAMES returns the names of the measured joint angles for
%  given Body markerset.  
%
% JOINTNAMES = WHICHJOINTNAMES(MARKERSET_NAME)
%
% INPUTS: MARKERSET_NAME = String.
% {'CriticalMarkers','CriticalMarkers_Elbow'
%                           'CriticalMarkers_M1'
%                           'CriticalMarkers_M1_Elbow','Full_markerset'}
%           MARKERSET_NAME should match the experiment.software.markerset
%           for the Body.
%
% OUTPUTS: JOINTNAMES = Cell array of strings.

switch Markerset_name
    case {'CriticalMarkers','CriticalMarkers_Elbow'}
        jointnames = {'shoulder_elevation_r','elevation_angle_r',...
            'shoulder_rotation_r','elbow_flexion_r','pro_supination_r',...
            'wrist_flexion_r','wrist_deviation_r'};
    case {'CriticalMarkers_M1','CriticalMarkers_M1_Elbow'}
        jointnames = {'shoulder_elevation_r','elevation_angle_r',...
            'shoulder_rotation_r','elbow_flexion_r','pro_supination_r',...
            'wrist_flexion_r','wrist_deviation_r',...
            'thumb_prox_flexion_r','thumb_prox_abduction_r',...
            'middle_prox_flexion_r','middle_prox_abduction_r',...
            'pinky_prox_flexion_r','pinky_prox_abduction_r'};
    case {'CriticalMarkers_M1_M2_Elbow'}
        jointnames = {'shoulder_elevation_r','elevation_angle_r',...
            'shoulder_rotation_r','elbow_flexion_r','pro_supination_r',...
            'wrist_flexion_r','wrist_deviation_r',...
            'thumb_prox_flexion_r','thumb_prox_abduction_r',...
            'thumb_mid_flexion_r','thumb_distal_flexion_r',...
            'middle_prox_flexion_r','middle_prox_abduction_r',...
            'middle_mid_flexion_r','middle_distal_flexion_r',...
            'pinky_prox_flexion_r','pinky_prox_abduction_r',...
            'pinky_mid_flexion_r','pinky_distal_flexion_r'};
    case {'Full_Markerset'}
        jointnames = {'shoulder_elevation_r','elevation_angle_r',...
            'shoulder_rotation_r','elbow_flexion_r','pro_supination_r',...
            'wrist_flexion_r','wrist_deviation_r',...
            'thumb_prox_flexion_r','thumb_prox_abduction_r',...
            'thumb_mid_flexion_r','thumb_distal_flexion_r',...
            'index_prox_flexion_r','index_prox_abduction_r',...
            'index_mid_flexion_r','index_distal_flexion_r',...
            'middle_prox_flexion_r','middle_prox_abduction_r',...
            'middle_mid_flexion_r','middle_distal_flexion_r',...
            'ring_prox_flexion_r','ring_prox_abduction_r',...
            'ring_mid_flexion_r','ring_distal_flexion_r',...
            'pinky_prox_flexion_r','pinky_prox_abduction_r',...
            'pinky_mid_flexion_r','pinky_distal_flexion_r'};
    otherwise
        disp(['Markerset not found: ' Markerset_name])
        jointnames = {};
end
