function Session = StoSSFF(InputSession, Chamber1, Ch1, Contact1, Chamber2, Ch2, Contact2, Chamber3, Ch3, Contact3, Task, N)
%
%   Session = StoSFF(InputSession,Chamber1,Ch1,Task,N)
%
%  Needs to be updated to allow contact inputs

global MONKEYDIR

if nargin < 2; Chamber1 = []; end
if nargin < 3; Ch1 = []; end
if nargin < 4; Contact1 = []; end
if nargin < 5; Chamber2 = []; end
if nargin < 6; Ch2 = []; end
if nargin < 7; Contact2 = []; end
if nargin < 8; Chamber3 = []; end
if nargin < 9; Ch3 = []; end
if nargin < 10; Contact3 = []; end
if nargin < 11; Task = []; end

Session = loadSpikeSpikeFieldField_Database;

Ind = [];
for iSess = 1:length(Session)
    SpikeSessNum1 = Session{iSess}{6}(1);
    SpikeSessNum2 = Session{iSess}{6}(2);
    if SpikeSessNum1 == InputSession{6}(1) || SpikeSessNum2 == InputSession{6}(1)
        if SpikeSessNum1 == InputSession{6}(1) && SpikeSessNum2 ~= InputSession{6}(1)
            Sind = 2; SpikeSessNum = SpikeSessNum1;
        elseif SpikeSessNum1 ~= InputSession{6}(1) && SpikeSessNum2 == InputSession{6}(1)
            Sind = 1; SpikeSessNum = SpikeSessNum2;
        end
        if ~isempty(Chamber1) || ~isempty(Chamber2) || ~isempty(Chamber3)
            Chambers = sessTower(Session{iSess});
            SpikeChamber1 = Chambers{Sind};
            FieldChamber2 = Chambers{3};
            FieldChamber3 = Chambers{4};
            if iscell(SpikeChamber1); SpikeChamber1 = SpikeChamber1{1}; end
            if iscell(FieldChamber2); FieldChamber2 = FieldChamber2{1}; end
            if iscell(FieldChamber3); FieldChamber3 = FieldChamber3{1}; end
        end
        if ~isempty(Ch1) || ~isempty(Ch2) || ~isempty(Ch3)
            Channels = sessElectrode(Session{iSess});
            SpikeCh1 = Channels(Sind);
            FieldCh2 = Channels(3);
            FieldCh3 = Channels(4);
        end
        if ~isempty(Contact1) || ~isempty(Contact2) || ~isempty(Contact3)
            Contacts = sessContact(Session{iSess});
            SpikeContact1 = Contacts{Sind};
            FieldContact2 = Contacts{3};
            FieldContact3 = Contacts{4};
        end
        if ~isempty(Chamber3)
            if ~isempty(Ch3)
                if ~isempty(Contact3)
                    if ~isempty(Chamber2)
                        if ~isempty(Ch2)
                            if ~isempty(Contact2)
                                if ~isempty(Chamber1)
                                    if ~isempty(Ch1)
                                        if ~isempty(Contact1)
                                            if SpikeSessNum == InputSession{6}(1) && ...
                                                    (strcmp(SpikeChamber1,Chamber1) || ...
                                                    (strcmp(SpikeChamber1(1:2),Chamber1(1:2)) && ...
                                                    strcmp(SpikeChamber1(end),Chamber1(end)))) && SpikeCh1==Ch1 && SpikeContact1==Contact1 && ...
                                                    (strcmp(FieldChamber2,Chamber2) || ...
                                                    (strcmp(FieldChamber2(1:2),Chamber2(1:2)) && ...
                                                    strcmp(FieldChamber2(end),Chamber2(end)))) && FieldCh2==Ch2 && FieldContact2==Contact2 && ...
                                                    (strcmp(FieldChamber3,Chamber3) || ...
                                                    (strcmp(FieldChamber3(1:2),Chamber3(1:2)) && ...
                                                    strcmp(FieldChamber3(end),Chamber3(end)))) && FieldCh3==Ch3 && FieldContact3==Contact3;
                                                Ind = [Ind,iSess];
                                            end
                                        else
                                            if SpikeSessNum == InputSession{6}(1) && ...
                                                    (strcmp(SpikeChamber1,Chamber1) || ...
                                                    (strcmp(SpikeChamber1(1:2),Chamber1(1:2)) && ...
                                                    strcmp(SpikeChamber1(end),Chamber1(end)))) && SpikeCh1==Ch1 && ...
                                                    (strcmp(FieldChamber2,Chamber2) || ...
                                                    (strcmp(FieldChamber2(1:2),Chamber2(1:2)) && ...
                                                    strcmp(FieldChamber2(end),Chamber2(end)))) && FieldCh2==Ch2 && FieldContact2==Contact2 && ...
                                                    (strcmp(FieldChamber3,Chamber3) || ...
                                                    (strcmp(FieldChamber3(1:2),Chamber3(1:2)) && ...
                                                    strcmp(FieldChamber3(end),Chamber3(end)))) && FieldCh3==Ch3 && FieldContact3==Contact3;
                                                Ind = [Ind,iSess];
                                            end
                                            
                                        end
                                    else
                                        if SpikeSessNum == InputSession{6}(1) && ...
                                                (strcmp(SpikeChamber1,Chamber1) || ...
                                                (strcmp(SpikeChamber1(1:2),Chamber1(1:2)) && ...
                                                strcmp(SpikeChamber1(end),Chamber1(end)))) && ...
                                                (strcmp(FieldChamber2,Chamber2) || ...
                                                (strcmp(FieldChamber2(1:2),Chamber2(1:2)) && ...
                                                strcmp(FieldChamber2(end),Chamber2(end)))) && FieldCh2==Ch2 && FieldContact2==Contact2 && ...
                                                (strcmp(FieldChamber3,Chamber3) || ...
                                                (strcmp(FieldChamber3(1:2),Chamber3(1:2)) && ...
                                                strcmp(FieldChamber3(end),Chamber3(end)))) && FieldCh3==Ch3 && FieldContact3==Contact3;
                                            Ind = [Ind,iSess];
                                        end
                                    end
                                else
                                    if ~isempty(Ch1)
                                        if ~isempty(Contact1)
                                            if SpikeSessNum == InputSession{6}(1) && ...
                                                    SpikeCh1==Ch1 && SpikeContact1==Contact1 && ...
                                                    (strcmp(FieldChamber2,Chamber2) || ...
                                                    (strcmp(FieldChamber2(1:2),Chamber2(1:2)) && ...
                                                    strcmp(FieldChamber2(end),Chamber2(end)))) && FieldCh2==Ch2 && FieldContact2==Contact2 && ...
                                                    (strcmp(FieldChamber3,Chamber3) || ...
                                                    (strcmp(FieldChamber3(1:2),Chamber3(1:2)) && ...
                                                    strcmp(FieldChamber3(end),Chamber3(end)))) && FieldCh3==Ch3 && FieldContact3==Contact3;
                                                Ind = [Ind,iSess];
                                            end
                                        else
                                            if SpikeSessNum == InputSession{6}(1) && ...
                                                    SpikeCh1==Ch1 && ...
                                                    (strcmp(FieldChamber2,Chamber2) || ...
                                                    (strcmp(FieldChamber2(1:2),Chamber2(1:2)) && ...
                                                    strcmp(FieldChamber2(end),Chamber2(end)))) && FieldCh2==Ch2 && FieldContact2==Contact2 && ...
                                                    (strcmp(FieldChamber3,Chamber3) || ...
                                                    (strcmp(FieldChamber3(1:2),Chamber3(1:2)) && ...
                                                    strcmp(FieldChamber3(end),Chamber3(end)))) && FieldCh3==Ch3 && FieldContact3==Contact3;
                                                Ind = [Ind,iSess];
                                            end
                                        end
                                    else
                                        if SpikeSessNum == InputSession{6}(1) && ...
                                                (strcmp(FieldChamber2,Chamber2) || ...
                                                (strcmp(FieldChamber2(1:2),Chamber2(1:2)) && ...
                                                strcmp(FieldChamber2(end),Chamber2(end)))) && FieldCh2==Ch2 && FieldContact2==Contact2 && ...
                                                (strcmp(FieldChamber3,Chamber3) || ...
                                                (strcmp(FieldChamber3(1:2),Chamber3(1:2)) && ...
                                                strcmp(FieldChamber3(end),Chamber3(end)))) && FieldCh3==Ch3 && FieldContact3==Contact3;
                                            Ind = [Ind,iSess];
                                        end
                                    end
                                end
                            else
                                if SpikeSessNum == InputSession{6}(1) && ...
                                        (strcmp(FieldChamber2,Chamber2) || ...
                                        (strcmp(FieldChamber2(1:2),Chamber2(1:2)) && ...
                                        strcmp(FieldChamber2(end),Chamber2(end)))) && FieldCh2==Ch2 && ...
                                        (strcmp(FieldChamber3,Chamber3) || ...
                                        (strcmp(FieldChamber3(1:2),Chamber3(1:2)) && ...
                                        strcmp(FieldChamber3(end),Chamber3(end)))) && FieldCh3==Ch3 && FieldContact3==Contact3;
                                    Ind = [Ind,iSess];
                                end
                            end
                        else
                            if ~isempty(Chamber1)
                                if ~isempty(Ch1)
                                    if ~isempty(Contact1)
                                        if SpikeSessNum == InputSession{6}(1) && ...
                                                (strcmp(SpikeChamber1,Chamber1) || ...
                                                (strcmp(SpikeChamber1(1:2),Chamber1(1:2)) && ...
                                                strcmp(SpikeChamber1(end),Chamber1(end)))) && SpikeCh1==Ch1 && SpikeContact1==Contact1 && ...
                                                (strcmp(FieldChamber2,Chamber2) || ...
                                                (strcmp(FieldChamber2(1:2),Chamber2(1:2)) && ...
                                                strcmp(FieldChamber2(end),Chamber2(end)))) && ...
                                                (strcmp(FieldChamber3,Chamber3) || ...
                                                (strcmp(FieldChamber3(1:2),Chamber3(1:2)) && ...
                                                strcmp(FieldChamber3(end),Chamber3(end)))) && FieldCh3==Ch3 && FieldContact3==Contact3;
                                            Ind = [Ind,iSess];
                                        end
                                    else
                                        if SpikeSessNum == InputSession{6}(1) && ...
                                                (strcmp(SpikeChamber1,Chamber1) || ...
                                                (strcmp(SpikeChamber1(1:2),Chamber1(1:2)) && ...
                                                strcmp(SpikeChamber1(end),Chamber1(end)))) && SpikeCh1==Ch1 && ...
                                                (strcmp(FieldChamber2,Chamber2) || ...
                                                (strcmp(FieldChamber2(1:2),Chamber2(1:2)) && ...
                                                strcmp(FieldChamber2(end),Chamber2(end)))) && ...
                                                (strcmp(FieldChamber3,Chamber3) || ...
                                                (strcmp(FieldChamber3(1:2),Chamber3(1:2)) && ...
                                                strcmp(FieldChamber3(end),Chamber3(end)))) && FieldCh3==Ch3 && FieldContact3==Contact3;
                                            Ind = [Ind,iSess];
                                        end
                                    end
                                else
                                    if SpikeSessNum == InputSession{6}(1) && ...
                                            (strcmp(SpikeChamber1,Chamber1) || ...
                                            (strcmp(SpikeChamber1(1:2),Chamber1(1:2)) && ...
                                            strcmp(SpikeChamber1(end),Chamber1(end)))) && ...
                                            (strcmp(FieldChamber2,Chamber2) || ...
                                            (strcmp(FieldChamber2(1:2),Chamber2(1:2)) && ...
                                            strcmp(FieldChamber2(end),Chamber2(end)))) &&  ...
                                            (strcmp(FieldChamber3,Chamber3) || ...
                                            (strcmp(FieldChamber3(1:2),Chamber3(1:2)) && ...
                                            strcmp(FieldChamber3(end),Chamber3(end)))) && FieldCh3==Ch3 && FieldContact3==Contact3;
                                        Ind = [Ind,iSess];
                                    end
                                end
                            else
                                if SpikeSessNum == InputSession{6}(1) && ...
                                        (strcmp(FieldChamber2,Chamber2) || ...
                                        (strcmp(FieldChamber2(1:2),Chamber2(1:2)) && ...
                                        strcmp(FieldChamber2(end),Chamber2(end)))) && ...
                                        (strcmp(FieldChamber3,Chamber3) || ...
                                        (strcmp(FieldChamber3(1:2),Chamber3(1:2)) && ...
                                        strcmp(FieldChamber3(end),Chamber3(end)))) && FieldCh3==Ch3 && FieldContact3==Contact3;
                                    Ind = [Ind,iSess];
                                end
                            end
                        end
                    else
                        if ~isempty(Chamber1)
                            if ~isempty(Ch1)
                                if ~isempty(Contact1)
                                    if SpikeSessNum == InputSession{6}(1) && ...
                                            (strcmp(SpikeChamber1,Chamber1) || ...
                                            (strcmp(SpikeChamber1(1:2),Chamber1(1:2)) && ...
                                            strcmp(SpikeChamber1(end),Chamber1(end)))) && SpikeCh1==Ch1 && SpikeContact1==Contact1 && ...
                                            (strcmp(FieldChamber3,Chamber3) || ...
                                            (strcmp(FieldChamber3(1:2),Chamber3(1:2)) && ...
                                            strcmp(FieldChamber3(end),Chamber3(end)))) && FieldCh3==Ch3 && FieldContact3==Contact3;
                                        Ind = [Ind,iSess];
                                    end
                                else
                                    if SpikeSessNum == InputSession{6}(1) && ...
                                            (strcmp(SpikeChamber1,Chamber1) || ...
                                            (strcmp(SpikeChamber1(1:2),Chamber1(1:2)) && ...
                                            strcmp(SpikeChamber1(end),Chamber1(end)))) && SpikeCh1==Ch1 && ...
                                            (strcmp(FieldChamber3,Chamber3) || ...
                                            (strcmp(FieldChamber3(1:2),Chamber3(1:2)) && ...
                                            strcmp(FieldChamber3(end),Chamber3(end)))) && FieldCh3==Ch3 && FieldContact3==Contact3;
                                        Ind = [Ind,iSess];
                                    end
                                end
                            else
                                if SpikeSessNum == InputSession{6}(1) && ...
                                        (strcmp(SpikeChamber1,Chamber1) || ...
                                        (strcmp(SpikeChamber1(1:2),Chamber1(1:2)) && ...
                                        strcmp(SpikeChamber1(end),Chamber1(end)))) && ...
                                        (strcmp(FieldChamber3,Chamber3) || ...
                                        (strcmp(FieldChamber3(1:2),Chamber3(1:2)) && ...
                                        strcmp(FieldChamber3(end),Chamber3(end)))) && FieldCh3==Ch3 && FieldContact3==Contact3;
                                    Ind = [Ind,iSess];
                                end
                            end
                        else
                            if SpikeSessNum == InputSession{6}(1) && ...
                                    (strcmp(FieldChamber3,Chamber3) || ...
                                    (strcmp(FieldChamber3(1:2),Chamber3(1:2)) && ...
                                    strcmp(FieldChamber3(end),Chamber3(end)))) && FieldCh3==Ch3 && FieldContact3==Contact3;
                                Ind = [Ind,iSess];
                            end
                        end
                    end
                else
                    if ~isempty(Chamber2)
                        if ~isempty(Ch2)
                            if ~isempty(Contact2)
                                if ~isempty(Chamber1)
                                    if ~isempty(Ch1)
                                        if ~isempty(Contact1)
                                            if SpikeSessNum == InputSession{6}(1) && ...
                                                    (strcmp(SpikeChamber1,Chamber1) || ...
                                                    (strcmp(SpikeChamber1(1:2),Chamber1(1:2)) && ...
                                                    strcmp(SpikeChamber1(end),Chamber1(end)))) && SpikeCh1==Ch1 && SpikeContact1==Contact1 && ...
                                                    (strcmp(FieldChamber2,Chamber2) || ...
                                                    (strcmp(FieldChamber2(1:2),Chamber2(1:2)) && ...
                                                    strcmp(FieldChamber2(end),Chamber2(end)))) && FieldCh2==Ch2 && FieldContact2==Contact2 && ...
                                                    (strcmp(FieldChamber3,Chamber3) || ...
                                                    (strcmp(FieldChamber3(1:2),Chamber3(1:2)) && ...
                                                    strcmp(FieldChamber3(end),Chamber3(end)))) && FieldCh3==Ch3;
                                                Ind = [Ind,iSess];
                                            end
                                        else
                                            if SpikeSessNum == InputSession{6}(1) && ...
                                                    (strcmp(SpikeChamber1,Chamber1) || ...
                                                    (strcmp(SpikeChamber1(1:2),Chamber1(1:2)) && ...
                                                    strcmp(SpikeChamber1(end),Chamber1(end)))) && SpikeCh1==Ch1 && ...
                                                    (strcmp(FieldChamber2,Chamber2) || ...
                                                    (strcmp(FieldChamber2(1:2),Chamber2(1:2)) && ...
                                                    strcmp(FieldChamber2(end),Chamber2(end)))) && FieldCh2==Ch2 && FieldContact2==Contact2 && ...
                                                    (strcmp(FieldChamber3,Chamber3) || ...
                                                    (strcmp(FieldChamber3(1:2),Chamber3(1:2)) && ...
                                                    strcmp(FieldChamber3(end),Chamber3(end)))) && FieldCh3==Ch3;
                                                Ind = [Ind,iSess];
                                            end
                                        end
                                    else
                                        if SpikeSessNum == InputSession{6}(1) && ...
                                                (strcmp(SpikeChamber1,Chamber1) || ...
                                                (strcmp(SpikeChamber1(1:2),Chamber1(1:2)) && ...
                                                strcmp(SpikeChamber1(end),Chamber1(end)))) && ...
                                                (strcmp(FieldChamber2,Chamber2) || ...
                                                (strcmp(FieldChamber2(1:2),Chamber2(1:2)) && ...
                                                strcmp(FieldChamber2(end),Chamber2(end)))) && FieldCh2==Ch2 && FieldContact2==Contact2 && ...
                                                (strcmp(FieldChamber3,Chamber3) || ...
                                                (strcmp(FieldChamber3(1:2),Chamber3(1:2)) && ...
                                                strcmp(FieldChamber3(end),Chamber3(end)))) && FieldCh3==Ch3;
                                            Ind = [Ind,iSess];
                                        end
                                    end
                                else
                                    if SpikeSessNum == InputSession{6}(1) && ...
                                            (strcmp(FieldChamber2,Chamber2) || ...
                                            (strcmp(FieldChamber2(1:2),Chamber2(1:2)) && ...
                                            strcmp(FieldChamber2(end),Chamber2(end)))) && FieldCh2==Ch2 && FieldContact2==Contact2 && ...
                                            (strcmp(FieldChamber3,Chamber3) || ...
                                            (strcmp(FieldChamber3(1:2),Chamber3(1:2)) && ...
                                            strcmp(FieldChamber3(end),Chamber3(end)))) && FieldCh3==Ch3;
                                        Ind = [Ind,iSess];
                                    end
                                    
                                end
                            else
                                if SpikeSessNum == InputSession{6}(1) && ...
                                        (strcmp(SpikeChamber1,Chamber1) || ...
                                        (strcmp(SpikeChamber1(1:2),Chamber1(1:2)) && ...
                                        strcmp(SpikeChamber1(end),Chamber1(end)))) && SpikeCh1==Ch1 && SpikeContact1==Contact1 && ...
                                        (strcmp(FieldChamber2,Chamber2) || ...
                                        (strcmp(FieldChamber2(1:2),Chamber2(1:2)) && ...
                                        strcmp(FieldChamber2(end),Chamber2(end)))) && FieldCh2==Ch2 && ...
                                        (strcmp(FieldChamber3,Chamber3) || ...
                                        (strcmp(FieldChamber3(1:2),Chamber3(1:2)) && ...
                                        strcmp(FieldChamber3(end),Chamber3(end)))) && FieldCh3==Ch3;
                                    Ind = [Ind,iSess];
                                end
                            end
                        else
                            if SpikeSessNum == InputSession{6}(1) && ...
                                    (strcmp(SpikeChamber1,Chamber1) || ...
                                    (strcmp(SpikeChamber1(1:2),Chamber1(1:2)) && ...
                                    strcmp(SpikeChamber1(end),Chamber1(end)))) && SpikeCh1==Ch1 && SpikeContact1==Contact1 && ...
                                    (strcmp(FieldChamber2,Chamber2) || ...
                                    (strcmp(FieldChamber2(1:2),Chamber2(1:2)) && ...
                                    strcmp(FieldChamber2(end),Chamber2(end)))) && ...
                                    (strcmp(FieldChamber3,Chamber3) || ...
                                    (strcmp(FieldChamber3(1:2),Chamber3(1:2)) && ...
                                    strcmp(FieldChamber3(end),Chamber3(end)))) && FieldCh3==Ch3;
                                Ind = [Ind,iSess];
                            end
                        end
                    else
                        if SpikeSessNum == InputSession{6}(1) && ...
                                (strcmp(FieldChamber3,Chamber3) || ...
                                (strcmp(FieldChamber3(1:2),Chamber3(1:2)) && ...
                                strcmp(FieldChamber3(end),Chamber3(end)))) && FieldCh3==Ch3;
                            Ind = [Ind,iSess];
                        end
                    end
                end
            else
                if SpikeSessNum == InputSession{6}(1) && ...
                        (strcmp(FieldChamber3,Chamber3) || ...
                        (strcmp(FieldChamber3(1:2),Chamber3(1:2)) && ...
                        strcmp(FieldChamber3(end),Chamber3(end))));
                    Ind = [Ind,iSess];
                end
            end
        else
            if SpikeSessNum == InputSession{6}(1)
                Ind = [Ind,iSess];
            end
        end
    end
end
Session = Session(Ind);

if ~isempty(Session)
    disp([num2str(length(Session)) ' SpikeSpikeFieldField Sessions']);
    %%%  Does the Task selection
    if ~isempty(Task)
        if ischar(Task); Task = {Task}; end
        load([MONKEYDIR '/mat/SpikeSpikeFieldField/SpikeSpikeFieldField_NumTrials.mat']);
        for iSess = 1:length(Session)
            SessionNumTrials = matchNumTrialsSession(NumTrials,Session{iSess});
            for iTask = 1:length(Task)
                TaskN(iSess,iTask) = SessionNumTrials.(Task{iTask});
            end
        end
        
        ind = zeros(length(Task),length(Session));
        for iTask = 1:length(Task)
            a = find(TaskN(:,iTask)>N(iTask));
            ind(iTask,a)=1;
        end
        ind = sum(ind,1);
        
        Ind = find(ind == length(Task));
        Session = Session(Ind);
        
        TaskString = '';
        for iTask = 1:length(Task)
            TaskString = [TaskString ' ' Task{iTask}];
        end
        disp([num2str(length(Session)) TaskString ' SpikeSpikeFieldField sessions']);
    else
        disp([num2str(length(Session)) ' SpikeSpikeFieldField sessions']);
    end
else
    disp('No SpikeSpikeFieldField Sessions');
end
