% TRAINKARMA   Generate a KARMA model from a prepared KARMA training set.
%  Trains a .mat style KARMA model for use with online and offline decoders
%  using lag vectors that have been generated by prepareKARMA.m
%
%  model=trainKARMA(karma, gamma, C)
%
%  karma is a a structure generated with prepareKARMA.m
%  gamma is the SVR gamma parameter (def .001)
%      C is the SVR C-slack parameter (def 1) % typo fixed by Rabadi 12/1/14 
%
function model=trainKARMA(karma, gamma, C)
if nargin<2
    gamma = .001;
    C = 1;
end

%% fit KARMA
tic
parfor i = 1:size(karma.Y,2)
    models{i} = svmtrain(karma.Y(:,i), karma.X,['-s 3 -t 2 -h 0 -g ' num2str(gamma) ' -p .1 -c ' num2str(C)]);
end
toc

% wts = model1.sv_coef'*model1.SVs;
% figure;plot(wts,'.')

model.params.n             = karma.params.n;
model.params.N             = karma.params.N;
model.params.m             = karma.params.m;
model.params.M             = karma.params.M;
model.params.latent_mean   = karma.params.latent_mean;
model.params.latent_std    = karma.params.latent_std;
model.params.observe_mean  = karma.params.observe_mean;
model.params.observe_std   = karma.params.observe_std;
model.params.libsvm_models = models;
model.hyperparams.m        = model.params.m;
model.hyperparams.n        = model.params.n;


